### ISSUE TITLE
cookies are duplicated for all LWP requests

### ISSUE THREAD

**Issue by dosprn** [olegwtf/p5-LWP-UserAgent-Cached#5]
I found all cookies are duplicated in requests if LWP::UserAgent:Cached module is used.
This issue could follow to problems on some web sites. You can reproduce this problem easily if you view requests in some kind of sniffer or use web site with cookies mirror.

I wrote a sample (see below) which first asks server mirror with Cache and second asks the same mirror without Cache.

`
use LWP::UserAgent;
use LWP::UserAgent::Cached;

my $ua =  LWP::UserAgent::Cached->new(cache_dir => '.');
my $res;

$ua->cookie_jar({});

print "Cached LWP request test\n";
print "First request for cookies, Server response contains 'Set-Cookie: Name=Value'\n";
$ua->get('http://check.dosprn.com/version/set_cookie.php');
print "Second request to cookie mirror.\n";
$res=$ua->get('http://check.dosprn.com/version/cookie.php');
print "Cached LWP request result: " . $res->decoded_content . "\n";

print "\n\n";

print "Native LWP request test\n";
$ua =  LWP::UserAgent->new();
$ua->cookie_jar({});
print "First request for cookies, Server response contains 'Set-Cookie: Name=Value'\n";
$ua->get('http://check.dosprn.com/version/set_cookie.php');

print "Second request to cookie mirror.\n";
$res=$ua->get('http://check.dosprn.com/version/cookie.php');
print "Native LWP request result: " .$res->decoded_content . "\n";
`

**Comment by olegwtf** [comment]
Fixed in 0.08
